services:
  postgres:
    image: postgres:17
    container_name: gerenciador-quadras-postgres
    restart: always

    environment:
      POSTGRES_DB: gerenciador_quadras
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
